POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de NodeJS 2025"
}

###
GET http://localhost:3333/courses

###
GET http://localhost:3333/courses/4f917be9-ff12-47bb-81a4-a3705f94619a

###
DELETE http://localhost:3333/courses/4f917be9-ff12-47bb-81a4-a3705f94619a
